### ISSUE TITLE
New logo for WatchSpace

### ISSUE THREAD

**Issue by reallinfo** [gogeorge/watch-space#1]
I wanted to contribute to WatchSpace. I designed a logo for WatchSpace. If you like it, I'll send you the files.

![watchspace](https://user-images.githubusercontent.com/36298335/37795020-e912c4a2-2e1b-11e8-85a4-a3c9d6c9a0bc.jpg)

**Comment by gogeorge** [comment]
Wow that's amazing. Sorry for my late response, I haven't opened github for a while and I actually never got the notification that you opened an issue. Sure send the files and I will add your logo and give you credit.

Although I don't know if watchspace still works; those CORS issues, nothing you can do about them
